-- Create other_events table schema
CREATE TABLE IF NOT EXISTS other_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL DEFAULT 'other', -- ideathon, meetup, design-competition, etc.
  status TEXT NOT NULL DEFAULT 'upcoming', -- upcoming, open, ended
  date TEXT, -- Display date string e.g. "Jan 20, 2026"
  end_date DATE, -- Actual end date for logic
  location TEXT,
  description TEXT, -- Short description for cards
  about TEXT, -- Full details/markdown content
  registration_link TEXT,
  image_url TEXT, -- Thumbnail
  banner_url TEXT, -- Hero banner
  attendees_count INTEGER DEFAULT 0,
  prize TEXT,
  is_public BOOLEAN DEFAULT TRUE,
  is_featured BOOLEAN DEFAULT FALSE,
  
  -- Extensible JSON columns for future-proofing
  organizers JSONB DEFAULT '[]'::jsonb,
  mentors JSONB DEFAULT '[]'::jsonb,
  schedule JSONB DEFAULT '[]'::jsonb,
  faq JSONB DEFAULT '[]'::jsonb,
  partners JSONB DEFAULT '[]'::jsonb,
  resources JSONB DEFAULT '[]'::jsonb
);

-- Add explicit indexes for performance
CREATE INDEX IF NOT EXISTS other_events_slug_idx ON other_events (slug);
CREATE INDEX IF NOT EXISTS other_events_status_idx ON other_events (status);
CREATE INDEX IF NOT EXISTS other_events_is_public_idx ON other_events (is_public);

-- Idempotent column additions (in case table exists but fields are missing)
DO $$ 
BEGIN 
    -- banner_url
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'banner_url') THEN 
        ALTER TABLE other_events ADD COLUMN banner_url TEXT; 
    END IF;

    -- about
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'about') THEN 
        ALTER TABLE other_events ADD COLUMN about TEXT; 
    END IF;

    -- end_date
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'end_date') THEN 
        ALTER TABLE other_events ADD COLUMN end_date DATE; 
    END IF;

    -- JSONB Columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'organizers') THEN 
        ALTER TABLE other_events ADD COLUMN organizers JSONB DEFAULT '[]'::jsonb; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'mentors') THEN 
        ALTER TABLE other_events ADD COLUMN mentors JSONB DEFAULT '[]'::jsonb; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'schedule') THEN 
        ALTER TABLE other_events ADD COLUMN schedule JSONB DEFAULT '[]'::jsonb; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'faq') THEN 
        ALTER TABLE other_events ADD COLUMN faq JSONB DEFAULT '[]'::jsonb; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'partners') THEN 
        ALTER TABLE other_events ADD COLUMN partners JSONB DEFAULT '[]'::jsonb; 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'other_events' AND column_name = 'resources') THEN 
        ALTER TABLE other_events ADD COLUMN resources JSONB DEFAULT '[]'::jsonb; 
    END IF;
END $$;
