-- Ensure workshops table has correct schema and permissions
-- Run this in Supabase SQL Editor

-- 1. Create table if not exists (or add missing columns manually if needed)
CREATE TABLE IF NOT EXISTS workshops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  banner_url TEXT,
  registration_link TEXT,
  date TEXT,
  location TEXT,
  slug TEXT UNIQUE,
  is_public BOOLEAN DEFAULT TRUE,
  is_featured BOOLEAN DEFAULT FALSE,
  topics TEXT[],
  schedule JSONB,
  mentors JSONB,
  faq JSONB,
  about TEXT,
  attendees_count INTEGER DEFAULT 0
);

-- 2. Enable RLS
ALTER TABLE workshops ENABLE ROW LEVEL SECURITY;

-- 3. Allow public read access (Crucial for frontend visibility)
DROP POLICY IF EXISTS "Public workshops are viewable by everyone" ON workshops;
CREATE POLICY "Public workshops are viewable by everyone" 
ON workshops FOR SELECT 
USING (true);

-- 4. Allow authenticated users (admins) full access
DROP POLICY IF EXISTS "Authenticated users can insert workshops" ON workshops;
CREATE POLICY "Authenticated users can insert workshops" 
ON workshops FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can update workshops" ON workshops;
CREATE POLICY "Authenticated users can update workshops" 
ON workshops FOR UPDATE 
USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can delete workshops" ON workshops;
CREATE POLICY "Authenticated users can delete workshops" 
ON workshops FOR DELETE 
USING (auth.role() = 'authenticated');
