-- Create tags table
CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    color TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public tags are viewable by everyone" 
ON tags FOR SELECT USING (true);

CREATE POLICY "Only admins can manage tags" 
ON tags FOR ALL USING (
    auth.role() = 'authenticated' -- In a real app, you'd check for an admin flag
);

-- Initial seed tags based on common hackathon themes
INSERT INTO tags (name, color) VALUES 
('AI/ML', '#9BE600'),
('Web3', '#9BE600'),
('Fintech', '#9BE600'),
('Open Source', '#9BE600'),
('Beginner Friendly', '#9BE600'),
('Healthtech', '#9BE600'),
('Sustainability', '#9BE600')
ON CONFLICT (name) DO NOTHING;
