-- Create workshops table
CREATE TABLE IF NOT EXISTS public.workshops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    date TEXT, -- Using TEXT for flexibility as seen in other tables, or TIMESTAMP
    location TEXT,
    registration_link TEXT,
    is_public BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    attendees_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.workshops ENABLE ROW LEVEL SECURITY;

-- Allow public read access to public workshops
CREATE POLICY "Allow public read access to public workshops"
ON public.workshops
FOR SELECT
USING (is_public = true);

-- Allow authenticated users (admins) full access
CREATE POLICY "Allow authenticated full access to workshops"
ON public.workshops
FOR ALL
USING (auth.role() = 'authenticated');

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_workshops_is_public ON public.workshops(is_public);
CREATE INDEX IF NOT EXISTS idx_workshops_is_featured ON public.workshops(is_featured);
CREATE INDEX IF NOT EXISTS idx_workshops_created_at ON public.workshops(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_workshops_date ON public.workshops(date);

-- Trigger for updated_at
CREATE TRIGGER set_workshops_updated_at
    BEFORE UPDATE ON public.workshops
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Grant permissions
GRANT ALL ON public.workshops TO authenticated;
GRANT SELECT ON public.workshops TO anon;

-- Metadata comments
COMMENT ON TABLE public.workshops IS 'Storage for hands-on learning sessions led by experts';
